# ============================================================
#   ft_transcendence — Makefile
#   Run `make help` to see what's available.
# ============================================================

COMPOSE	   := docker compose
COMPOSE_PROD  := -f docker-compose.yml
COMPOSE_DEV   := -f docker-compose.yml -f docker-compose.dev.yml

CERT_DIR	  := nginx/certs
CERT_KEY	  := $(CERT_DIR)/selfsigned.key
CERT_CRT	  := $(CERT_DIR)/selfsigned.crt

# 'docker compose down' removes containers by project label and stays quiet
# about the ones already gone. At 42, 'docker compose' is podman emulating the
# Docker CLI and delegating to podman-compose, which instead walks the
# container_name: list and shells out to 'podman stop'/'podman rm' per name --
# so every container a previous pass already removed prints an error. 'clean'
# has to run 'down' twice (docker-compose.dev.yml renames backend/frontend to
# ft_backend_dev/ft_frontend_dev, so the prod pass is the only one that can
# reach the prod names), which makes that chatter unavoidable. Filter exactly
# those lines plus podman's two banners; anything else still reaches the
# terminal. Matches nothing under real Docker -- it never emits these.
CLEAN_NOISE   := Error: no container with (name or ID|ID or name) .+ found|Emulate Docker CLI using podman|Executing external compose provider

# rm -rf that can unlink what the host user cannot. Under rootless podman a
# container's uid maps to a host *subuid*, so files npm wrote through the dev
# bind mounts are not ours to remove; inside the container we are root in that
# userns and do own them (this is 'podman unshare rm -rf' by another route).
# $(1) = host directory to mount, $(2) = paths to delete under /host.
RM_IN_CONTAINER = docker run --rm -v $(1):/host:z node:20-alpine rm -rf $(2)

# Default goal when running `make` with no args
.DEFAULT_GOAL := help

# ============================================================
#   Help
# ============================================================

help: ## Show this help message
	@echo ""
	@echo "  ft_transcendence — available targets:"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "	\033[36m%-14s\033[0m %s\n", $$1, $$2}'
	@echo ""

# ============================================================
#   First-time setup
# ============================================================

env: ## Create .env from .env.example if it does not exist
	@if [ ! -f .env ]; then \
		cp .env.example .env; \
		echo ".env created from .env.example — review it before running!"; \
	else \
		echo ".env already exists, skipping."; \
	fi
	@if [ ! -f monitoring/alertmanager/discord_webhook_url ]; then \
			  cp monitoring/alertmanager/discord_webhook_url.example monitoring/alertmanager/discord_webhook_url; \
			  echo "monitoring/alertmanager/discord_webhook_url created from example file, paste the Discord webhook URL into it!"; \
	  else \
			  echo "discord_webhook_url already exists, skipping."; \
	  fi

certs: $(CERT_CRT) ## Generate self-signed TLS certificates (idempotent)
	@# openssl creates the key 0600, readable only by the host user. The prod
	@# backend image runs as the non-root 'app' user (see backend/Dockerfile),
	@# so it would get EACCES on startup. Harmless here: throwaway self-signed
	@# cert for CN=localhost, regenerated by 'make certs'.
	@chmod 644 $(CERT_KEY)

$(CERT_CRT):
	@mkdir -p $(CERT_DIR)
	@echo "Generating self-signed certificates in $(CERT_DIR)..."
	@openssl req -x509 -nodes -newkey rsa:4096 \
		-keyout $(CERT_KEY) \
		-out $(CERT_CRT) \
		-days 365 \
		-subj "/C=FR/ST=IDF/L=Paris/O=42/OU=ft_transcendence/CN=localhost" \
		2>/dev/null
	@echo "Certificates ready."

# ============================================================
#   Production / evaluation (single-command requirement)
# ============================================================

up: env certs ## Build and start the stack in detached mode
	$(COMPOSE) $(COMPOSE_PROD) up --build -d
	@echo ""
	@echo "  Stack is up. Open https://localhost"
	@echo "  (Self-signed cert — your browser will warn, that's expected.)"
	@echo ""

down: ## Stop the stack (keeps volumes)
	$(COMPOSE) $(COMPOSE_PROD) down

re: down up ## Restart the stack from scratch

# ============================================================
#   Development (hot reload, bind mounts)
#   Requires docker-compose.dev.yml — to be added later.
# ============================================================

dev: env certs ## Start the stack in development mode (foreground, hot reload)
	$(COMPOSE) $(COMPOSE_DEV) up --build

dev-down: ## Stop the dev stack
	$(COMPOSE) $(COMPOSE_DEV) down

# ============================================================
#   Dev workflow shortcuts
# ============================================================

test-backend: ## Run backend tests
	$(COMPOSE) $(COMPOSE_DEV) exec backend npm test

test-frontend: ## Run frontend tests
	$(COMPOSE) $(COMPOSE_DEV) exec frontend npm test

lint-backend: ## Lint backend
	$(COMPOSE) $(COMPOSE_DEV) exec backend npm run lint

lint-frontend: ## Lint frontend
	$(COMPOSE) $(COMPOSE_DEV) exec frontend npm run lint

sh-backend: ## Open a shell inside the backend container
	$(COMPOSE) $(COMPOSE_DEV) exec backend sh

sh-frontend: ## Open a shell inside the frontend container
	$(COMPOSE) $(COMPOSE_DEV) exec frontend sh

sh-db: ## Open psql inside the postgres container
	$(COMPOSE) $(COMPOSE_DEV) exec postgres sh -c 'psql -U "$$POSTGRES_USER" -d ft_transcendence'

# ============================================================
#   Database (Prisma)
# ============================================================

migrate: ## Apply pending migrations inside the backend container
	$(COMPOSE) $(COMPOSE_PROD) exec backend npx prisma migrate deploy

migrate-dev: ## Create a new migration from schema changes (dev only)
	$(COMPOSE) $(COMPOSE_DEV) exec backend npx prisma migrate dev

studio: ## Open Prisma Studio (browse the DB)
	$(COMPOSE) $(COMPOSE_DEV) exec backend npx prisma studio

# ============================================================
#   Inspection
# ============================================================

logs: ## Tail logs from all services
	$(COMPOSE) $(COMPOSE_PROD) logs -f

ps: ## List running containers
	$(COMPOSE) $(COMPOSE_PROD) ps

# ============================================================
#   Cleanup
# ============================================================

clean: ## Stop everything and remove named volumes (wipes the DB!)
	@# Best-effort by design: fclean must reach its rm/prune even if an engine
	@# is missing or a stack was never up, so both passes swallow their status.
	@# See CLEAN_NOISE above for what gets filtered and why.
	@echo "Stopping the dev stack and removing its volumes..."
	@$(COMPOSE) $(COMPOSE_DEV) down -v 2>&1 | grep -vE '$(CLEAN_NOISE)' || true
	@echo "Stopping the prod stack and removing its volumes..."
	@$(COMPOSE) $(COMPOSE_PROD) down -v 2>&1 | grep -vE '$(CLEAN_NOISE)' || true

fclean: clean ## Full clean: also remove certs and prune Docker images
	rm -rf $(CERT_DIR)
	@# node_modules and backend/dist are container artefacts. When the dev image
	@# runs as USER node (uid 1000) under Docker they land owned by the host user
	@# and plain rm works. Two cases where it does not: trees left by images built
	@# before that switch are root-owned, and under rootless podman the container
	@# uid maps to a host subuid we cannot unlink either. Both need a container
	@# that *is* root in the relevant userns -- hence the fallback, which also
	@# spares us re-pulling node:20-alpine after every prune -af below.
	@# Leading '-': a missing engine must not skip the prune below.
	-rm -rf frontend/node_modules 2>/dev/null || \
		$(call RM_IN_CONTAINER,$(CURDIR)/frontend,/host/node_modules)
	-rm -rf backend/dist backend/node_modules 2>/dev/null || \
		$(call RM_IN_CONTAINER,$(CURDIR)/backend,/host/dist /host/node_modules)
	docker system prune -af

.PHONY: help env certs up down re dev dev-down migrate migrate-dev studio logs \
	ps clean fclean test-backend test-frontend lint-backend lint-frontend \
	sh-backend sh-frontend sh-db
