# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    alerts.yml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jbaumfal < jbaumfal@student.42.fr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/08/02 19:43:04 by jbaumfal          #+#    #+#              #
#    Updated: 2026/08/02 19:43:10 by jbaumfal         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

groups: []